// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbdgiiaA6ASj--iuNgChCfA49z99yQ268',
    appId: '1:1028196754000:web:3afad21452ecd031aee755',
    messagingSenderId: '1028196754000',
    projectId: 'fyp-app-fe74d',
    authDomain: 'fyp-app-fe74d.firebaseapp.com',
    storageBucket: 'fyp-app-fe74d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYll2KV4TRotrC8UwWm27cvfsM4s7kX9k',
    appId: '1:1028196754000:android:21f7a19433025950aee755',
    messagingSenderId: '1028196754000',
    projectId: 'fyp-app-fe74d',
    storageBucket: 'fyp-app-fe74d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyEqjXzSXtZsFBDQPCAWzgcxQJ9v7K0Ok',
    appId: '1:1028196754000:ios:34e6729499d97e4daee755',
    messagingSenderId: '1028196754000',
    projectId: 'fyp-app-fe74d',
    storageBucket: 'fyp-app-fe74d.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyEqjXzSXtZsFBDQPCAWzgcxQJ9v7K0Ok',
    appId: '1:1028196754000:ios:34e6729499d97e4daee755',
    messagingSenderId: '1028196754000',
    projectId: 'fyp-app-fe74d',
    storageBucket: 'fyp-app-fe74d.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbdgiiaA6ASj--iuNgChCfA49z99yQ268',
    appId: '1:1028196754000:web:1cf0d023ba15bf91aee755',
    messagingSenderId: '1028196754000',
    projectId: 'fyp-app-fe74d',
    authDomain: 'fyp-app-fe74d.firebaseapp.com',
    storageBucket: 'fyp-app-fe74d.firebasestorage.app',
  );
}
